### ISSUE TITLE
Redundant Method

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-careerbuilder#1]
Hey @karllhughes 

In this Careerbuilder provider class, it implements a `getJobs` method that is identical to the part method in the Abstract class. Why is this?

https://github.com/JobBrander/jobs-careerbuilder/blob/master/src/Careerbuilder.php#L213

**Comment by karllhughes** [comment]
I had put it in there to test the provider before our update to the common project took effect, so it can be removed. In fact, I'll remove it now :-)
